# Site settings
title: MS Solutions | Crab Feeding
email: carl.haukas@ms-solutions.no
description: Introducing crab feeding on industrial scale.
baseurl: "/mss" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Identity
your-name: MS Solutions
your-title: Developing and manufacturing next generation aquaculture systems. Together, in your production - we can renew the crab industry and solve the challenges of tomorrow.

# Social settings
500px_url: mailto:carl.haukas@ms-solutions.no
facebook_url: https://facebook.com
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/company/ms-solutions-no
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
