# Site settings
title: MS Solutions
email: contact@ms-solutions.no
description: Introducing crab feeding on industrial scale.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ms-solutions.no" # the base hostname & protocol for your site

# Identity
your-name: MS Solutions
your-title: Introducing crab feeding on industrial scale

# Social settings
500px_url: mailto:contact@ms-solutions.no
facebook_url: https://facebook.com
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/company/ms-solutions-no
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
