# Site settings
title: MS Solutions | Thormøhlens gate 51, 5006 Bergen | Phone: (+47) 40634490
email: carl.haukas@ms-solutions.no
description: Introducing crab feeding on industrial scale.
baseurl: "/mss" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Identity
your-name: MS Solutions
your-title: Introducing crab feeding on industrial scale

# Social settings
500px_url: mailto:carl.haukas@ms-solutions.no
facebook_url: https://facebook.com
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/company/ms-solutions-as
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
